#!/bin/sh
# This is free and unencumbered software released into the public domain.
# For more information, please refer to <http://unlicense.org/>

#=======================================
w_new_option iup IUP
#=======================================

opt_print_iup()
{
	echo '  --with-iup-static       link the static IUP library'
}

opt_configure_iup()
{
	enable_iup_static=no

	for i in $@
	do
		case $i in
		--with-iup-static) enable_iup_static='yes' ;;
		esac
	done
}

opt_check_iup()
{
	if ! run_pkg_config iup --exists 2>/dev/null ; then
		exit_error "pkg-config: iup was not found"
	fi

	IUP_CFLAGS=$(run_pkg_config iup --cflags 2>/dev/null)
	if [ "$enable_iup_static" = "yes" ] ; then
		iup_pcfiledir=$(run_pkg_config iup --variable=pcfiledir 2>/dev/null)
		iup_libs_private=$(sed -n 's/^Libs\.private://p' "$iup_pcfiledir/iup.pc")
		IUP_LIBS="$(run_pkg_config iup --libs 2>/dev/null) $iup_libs_private"
		iup_requires=$(run_pkg_config iup --print-requires-private 2>/dev/null)
		if [ -n "$iup_requires" ] ; then
			IUP_LIBS="$IUP_LIBS $(run_pkg_config $iup_requires --libs 2>/dev/null)"
		fi
	else
		IUP_LIBS=$(run_pkg_config iup --libs 2>/dev/null)
	fi

	echo "checking for IUP... yes; version $(run_pkg_config iup --modversion 2>/dev/null)"

	config_h_have="$config_h_have IUP"
	config_mk_flags="$config_mk_flags IUP"
}
